### ISSUE TITLE
[BUG] Unable to add/pair new magichome devices

### ISSUE THREAD

**Issue by Zaacis** [Clivar/magichome-adapter#1]
**Describe the bug**
I can't get the magic light to populate as a thing. I tried auto-adding as well as manually inputting the ip. I see an error "400" appear on my attempts. The magic light can be pinged from the raspberry pi and there are no firewalls between the two.
On my end I see I have magic home version 0.0.2 which is the same version I had before the latest github update.

**To Reproduce**
1. Pair magic light to network.
2. Ensure I can ping magic light from raspberry pi.
3. Try manually inputting the ip on add-on. Its takes and I see (Errors undefined 400).
4. Try going directly to add a thing. Does not auto-find device.
5. Added a manual url (in my case 192.168.7.62). Does not find device.
6. Uninstall add-on and reinstall. Same results.
7. Try removing IP from step 3 and proceeding with step 4. Same result.

**Expected behavior**
Not to see an error on step 3 OR it working on step 5 above.

**Which Magic Home device**
- Rgbww

**Additional context**
Thank you in advance for your support!

**Comment by Clivar** [comment]
Hi Zaacis,

Thanks for bringing this to my attention. I noticed a ModuleNotFound error on a clean gateway install that replicated exactly what you are seeing in the interface. Apparently my development docker image had the package globally installed and a refactor messed with my imports.

I fixed it in 0.0.3 and is now available for download in the gateway.

Let me know if this fixed the issue :)

**Comment by Zaacis** [comment]
Hi Clivar,
Thank you for the rapid update and indeed it is now populating and I have control over the rgb colors.
Thank you,
Zaacis
